postgresql: &postgresql
  adapter: postgresql
  database: ch_panel
  username: <%=ENV['POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['POSTGRESQL_DB_HOST']%>
  port:     5432
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "postgresql" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
